version: "3.9"
services:
  server:
    image: bonk123123/folioport_server:0.0.1
    # build: ./server

    ports:
      - 5005:5005

  client:
    image: bonk123123/folioport_client:0.0.1
    # build: ./client

    ports:
      - 5021:5021
    
    depends_on:
      - server